name: "GitGuardian Shield Action"
description: "Scan commits for secrets and other issues."
branding:
  icon: "shield"
  color: "blue"
runs:
  using: "docker"
  image: "docker://gitguardian/ggshield:latest"
  args:
    - ggshield
    - scan
    - ci
